### ISSUE TITLE
assertion failed: !self.in_new_crate(old)

### ISSUE THREAD

**Issue by Eijebong** [rust-lang-nursery/rust-semverver#50]
When using `cargo semver` on [mozjs](https://github.com/servo/rust-mozjs) with an updated num-traits (so 0.2), I get the following ICE:

```
thread 'rustc' panicked at 'assertion failed: !self.in_new_crate(old)', src/semcheck/mapping.rs:170:9                                                          
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.                                                                        
stack backtrace:                                                                                                                                               
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace                                                                                                
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49                                                                                                  
   1: std::sys_common::backtrace::print                                                                                                                        
             at libstd/sys_common/backtrace.rs:71                                                                                                              
             at libstd/sys_common/backtrace.rs:59                                                                                                              
   2: std::panicking::default_hook::{{closure}}                                                                                                                
             at libstd/panicking.rs:207                                                                                                                        
   3: std::panicking::default_hook                                                                                                                             
             at libstd/panicking.rs:223                                                                                                                        
   4: core::ops::function::Fn::call                                                                                                                            
   5: std::panicking::rust_panic_with_hook                                                                                                                     
             at libstd/panicking.rs:403                                                                                                                        
   6: std::panicking::begin_panic                                                                                                                              
   7: semverver::semcheck::mapping::IdMapping::get_new_id                                                                                                      
   8: semverver::semcheck::translate::TranslationContext::translate_orig_substs                                                                                
   9: <rustc::ty::fold::BottomUpFolder<'a, 'gcx, 'tcx, F> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty                                                 
  10: semverver::semcheck::translate::TranslationContext::translate_orig_substs::{{closure}}                                                                   
  11: rustc::ty::subst::<impl rustc::ty::Slice<rustc::ty::subst::Kind<'tcx>>>::fill_item                                                                       
  12: rustc::ty::subst::<impl rustc::ty::Slice<rustc::ty::subst::Kind<'tcx>>>::for_item                                                                        
  13: semverver::semcheck::translate::TranslationContext::translate_orig_substs                                                                                
  14: <rustc::ty::fold::BottomUpFolder<'a, 'gcx, 'tcx, F> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty                                                 
  15: <rustc_data_structures::accumulate_vec::AccumulateVec<A> as core::iter::traits::FromIterator<<A as rustc_data_structures::array_vec::Array>::Element>>::f
rom_iter                                                                                                                                                       
  16: rustc::ty::fold::TypeFoldable::fold_with                                                                                                                 
  17: rustc::ty::structural_impls::<impl rustc::ty::fold::TypeFoldable<'tcx> for &'tcx rustc::ty::TyS<'tcx>>::super_fold_with                                  
  18: <rustc::ty::fold::BottomUpFolder<'a, 'gcx, 'tcx, F> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty                                                 
  19: <std::thread::local::LocalKey<T>>::with                                                                                                                  
  20: rustc::infer::InferCtxtBuilder::enter                                                                                                                    
  21: semverver::semcheck::traverse::run_analysis                                                                                                              
  22: <rust_semverver::SemVerVerCompilerCalls as rustc_driver::CompilerCalls<'a>>::build_controller::{{closure}}                                               
  23: rustc::dep_graph::graph::DepGraph::with_ignore                                                                                                           
  24: rustc_driver::driver::compile_input::{{closure}}                                                                                                         
  25: <std::thread::local::LocalKey<T>>::with                                                                                                                  
  26: <std::thread::local::LocalKey<T>>::with                                                                                                                  
  27: rustc::ty::context::TyCtxt::create_and_enter                                                                                                             
  28: rustc_driver::driver::compile_input                                                                                                                      
  29: rustc_driver::run_compiler_impl                                                                                                                          
  30: syntax::with_globals                                                                                                                                     
  31: rustc_driver::run_compiler

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0-nightly (55c984ee5 2018-03-16) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib


```

**Comment by ibabushkin** [comment]
Sorry for the late reply, I managed to reproduce the issue and I'm now working on constructing a minimal example. Stay tuned.

**Comment by ibabushkin** [comment]
This should be fixed now, please confirm :)

**Comment by Eijebong** [comment]
It fixes that error yeah :)
